/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsernameReposImport } from './routes/$username.Repos'
import { Route as UsernameRepoDashboardImport } from './routes/$username.$repo.Dashboard'
import { Route as UsernameRepoDashboardStatsImport } from './routes/$username.$repo.dashboard.stats'
import { Route as UsernameRepoDashboardGitTreeImport } from './routes/$username.$repo.dashboard.git-tree'
import { Route as UsernameRepoDashboardCommitsImport } from './routes/$username.$repo.dashboard.commits'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsernameReposRoute = UsernameReposImport.update({
  path: '/$username/Repos',
  getParentRoute: () => rootRoute,
} as any)

const UsernameRepoDashboardRoute = UsernameRepoDashboardImport.update({
  path: '/$username/$repo/Dashboard',
  getParentRoute: () => rootRoute,
} as any)

const UsernameRepoDashboardStatsRoute = UsernameRepoDashboardStatsImport.update(
  {
    path: '/$username/$repo/dashboard/stats',
    getParentRoute: () => rootRoute,
  } as any,
)

const UsernameRepoDashboardGitTreeRoute =
  UsernameRepoDashboardGitTreeImport.update({
    path: '/$username/$repo/dashboard/git-tree',
    getParentRoute: () => rootRoute,
  } as any)

const UsernameRepoDashboardCommitsRoute =
  UsernameRepoDashboardCommitsImport.update({
    path: '/$username/$repo/dashboard/commits',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$username/Repos': {
      preLoaderRoute: typeof UsernameReposImport
      parentRoute: typeof rootRoute
    }
    '/$username/$repo/Dashboard': {
      preLoaderRoute: typeof UsernameRepoDashboardImport
      parentRoute: typeof rootRoute
    }
    '/$username/$repo/dashboard/commits': {
      preLoaderRoute: typeof UsernameRepoDashboardCommitsImport
      parentRoute: typeof rootRoute
    }
    '/$username/$repo/dashboard/git-tree': {
      preLoaderRoute: typeof UsernameRepoDashboardGitTreeImport
      parentRoute: typeof rootRoute
    }
    '/$username/$repo/dashboard/stats': {
      preLoaderRoute: typeof UsernameRepoDashboardStatsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  UsernameReposRoute,
  UsernameRepoDashboardRoute,
  UsernameRepoDashboardCommitsRoute,
  UsernameRepoDashboardGitTreeRoute,
  UsernameRepoDashboardStatsRoute,
])

/* prettier-ignore-end */
